SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PROJ_ROOT := $(shell pwd)/../..
VERILOG_SOURCES += $(PROJ_ROOT)/verilog/clock_gen.v
TOPLEVEL = clock_gen
MODULE = test_clock
include $(shell cocotb-config --makefiles)/Makefile.sim