## ===================================================================
## PHYSICAL PIN CONSTRAINTS (Basys 3)
## ===================================================================

## Clock signal
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk_100MHz]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_100MHz]

## Switches
set_property -dict { PACKAGE_PIN V17  IOSTANDARD LVCMOS33 } [get_ports {sw[0]}]
set_property -dict { PACKAGE_PIN V16  IOSTANDARD LVCMOS33 } [get_ports {sw[1]}]

## Buttons
set_property -dict { PACKAGE_PIN U18  IOSTANDARD LVCMOS33 } [get_ports reset]

## Camera Data Pins
set_property -dict { PACKAGE_PIN P17  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[0]}]
set_property -dict { PACKAGE_PIN N17  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[1]}]
set_property -dict { PACKAGE_PIN M19  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[2]}]
set_property -dict { PACKAGE_PIN M18  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[3]}]
set_property -dict { PACKAGE_PIN L17  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[4]}]
set_property -dict { PACKAGE_PIN K17  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[5]}]
set_property -dict { PACKAGE_PIN C16  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[6]}]
set_property -dict { PACKAGE_PIN B16  IOSTANDARD LVCMOS33 } [get_ports {OV7670_D[7]}]

## Camera Control Pins
set_property -dict { PACKAGE_PIN A17  IOSTANDARD LVCMOS33 } [get_ports OV7670_HREF]
set_property -dict { PACKAGE_PIN A16  IOSTANDARD LVCMOS33 } [get_ports OV7670_PCLK]
set_property -dict { PACKAGE_PIN R18  IOSTANDARD LVCMOS33 } [get_ports OV7670_PWDN]
set_property -dict { PACKAGE_PIN P18  IOSTANDARD LVCMOS33 } [get_ports OV7670_RST]
set_property -dict { PACKAGE_PIN A14  IOSTANDARD LVCMOS33 } [get_ports OV7670_SCLK]
set_property -dict { PACKAGE_PIN A15  IOSTANDARD LVCMOS33 } [get_ports OV7670_SDAT]
set_property -dict { PACKAGE_PIN B15  IOSTANDARD LVCMOS33 } [get_ports OV7670_VSYNC]
set_property -dict { PACKAGE_PIN C15  IOSTANDARD LVCMOS33 } [get_ports OV7670_XCLK]

## CRITICAL: Allow the camera clock to enter through a standard PMOD pin
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7670_PCLK_IBUF]

## VGA Connector
set_property -dict { PACKAGE_PIN G19  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[8]}]
set_property -dict { PACKAGE_PIN H19  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[9]}]
set_property -dict { PACKAGE_PIN J19  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[10]}]
set_property -dict { PACKAGE_PIN N19  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[11]}]
set_property -dict { PACKAGE_PIN N18  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[0]}]
set_property -dict { PACKAGE_PIN L18  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[1]}]
set_property -dict { PACKAGE_PIN K18  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[2]}]
set_property -dict { PACKAGE_PIN J18  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[3]}]
set_property -dict { PACKAGE_PIN J17  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[4]}]
set_property -dict { PACKAGE_PIN H17  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[5]}]
set_property -dict { PACKAGE_PIN G17  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[6]}]
set_property -dict { PACKAGE_PIN D17  IOSTANDARD LVCMOS33 } [get_ports {vga_rgb[7]}]
set_property -dict { PACKAGE_PIN P19  IOSTANDARD LVCMOS33 } [get_ports vga_hsync]
set_property -dict { PACKAGE_PIN R19  IOSTANDARD LVCMOS33 } [get_ports vga_vsync]

## Configuration options
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]


## ===================================================================
## TIMING CONSTRAINTS (Fixes the Critical Methodology Warnings)
## ===================================================================

# 1. Define the custom 25 MHz clock generated by your clock_gen_inst (100MHz / 4)
create_generated_clock -name clk_25mhz_gen -source [get_ports clk_100MHz] -divide_by 4 [get_pins clock_gen_inst/counter_reg[1]/Q]

# 2. Define the slow 10 kHz I2C clock generated inside the IIC module (25MHz / 2500)
create_generated_clock -name i2c_slow_clk -source [get_pins clock_gen_inst/counter_reg[1]/Q] -divide_by 2500 [get_pins IIC/mI2C_CTRL_CLK_reg/Q]

# 3. Define the incoming camera pixel clock (Approx 24 MHz based on XCLK)
create_clock -period 41.667 -name cam_pclk -waveform {0 20.833} [get_ports OV7670_PCLK]

# 4. Tell Vivado it is safe to ignore timing paths between the asynchronous camera clock and our system clocks
set_clock_groups -asynchronous -group [get_clocks sys_clk_pin] -group [get_clocks cam_pclk]
set_clock_groups -asynchronous -group [get_clocks clk_25mhz_gen] -group [get_clocks cam_pclk]