# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/deepaung/Courses/hw-syn-lab-i/final-project/verilog/Basys-3-Master.xdc

# IP: ip/ila_data_out_1/ila_data_out.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_data_out || ORIG_REF_NAME==ila_data_out} -quiet] -quiet
