# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.srcs/sources_1/ip/ila_data_out/ila_data_out.xci
# IP: The module: 'ila_data_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.gen/sources_1/ip/ila_data_out/ila_data_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.srcs/sources_1/ip/ila_data_out/ila_data_out.xci
# IP: The module: 'ila_data_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/deepaung/Courses/hw-syn-lab-i/final-project/vivado/vivado.gen/sources_1/ip/ila_data_out/ila_data_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
